[package]
name = "mytodo"
version = "0.1.0"
authors = ["Martin Trejo Chavez <chilli.coder@gmail.com>"]
edition = "2018"

[workspace]
members = ["backend", "frontend"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }

